### ISSUE TITLE
unable to set position

### ISSUE THREAD

**Issue by zkrige** [yenoiwesa/homebridge-connexoon#28]
```
2021/02/12, 09:00:13] [My Connexoon Hub] Get RTS (16714958) target position success: 0
[2021/02/12, 09:00:17] [My Connexoon Hub] Set RTS (16714958) target position with value: 100
[2021/02/12, 09:00:18] [My Connexoon Hub] Set RTS (16714958) target position success: 100
[2021/02/12, 09:00:19] [My Connexoon Hub] Failed to exec command {
  errorCode: 'UNSUPPORTED_OPERATION',
  error: 'No such command : open on device rts://0407-4905-6283/16714958 (rts:UnknowRTSComponent)'
}
[2021/02/12, 09:00:19] [My Connexoon Hub] StatusCodeError: 400 - {"errorCode":"UNSUPPORTED_OPERATION","error":"No such command : open on device rts://0407-4905-6283/16714958 (rts:UnknowRTSComponent)"}
    at new StatusCodeError (/usr/lib/node_modules/homebridge-connexoon/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/lib/node_modules/homebridge-connexoon/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/lib/node_modules/homebridge-connexoon/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/lib/node_modules/homebridge-connexoon/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-connexoon/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-connexoon/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22) {
  statusCode: 400,
  error: {
    errorCode: 'UNSUPPORTED_OPERATION',
    error: 'No such command : open on device rts://0407-4905-6283/16714958 (rts:UnknowRTSComponent)'
  },
  options: {
    auth: {
      bearer: 'xxxxxxxxxxx'
    },
    url: 'https://tahomalink.com/enduser-mobile-web/enduserAPI/exec/apply',
    json: true,
```

**Comment by zkrige** [comment]
turns out the device wasn't properly configured on the Somfy portal - it seems to work now

**Comment by yenoiwesa** [comment]
Didn't even have time to reply hehe!
