### ISSUE TITLE
error  with homebridge 1.3.4

### ISSUE THREAD

**Issue by angladacamps** [yenoiwesa/homebridge-connexoon#30]
at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at CommunityTypes.EveResetTotal.Characteristic.toHAP (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:1293:24)
    at _loop_1 (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:601:24)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Service.js:450:21
    at new Promise (<anonymous>)
    at FakeGatoHistory.Service.toHAP (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:549:12)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1035:72
    at Array.map (<anonymous>)
    at Accessory.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1035:49)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at Accessory.toHAP (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:816:24)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1043:39
(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by yenoiwesa** [comment]
I am running Homebridge `1.3.4` with my home setup and everything is working fine. The error is at your end (as the stack trace suggests too, none of it is coming from this plugin).
