### ISSUE TITLE
Time out errors connecting to Somfy cloud server homebridge-connexoon

### ISSUE THREAD

**Issue by Zeses** [yenoiwesa/homebridge-connexoon#81]
Every hour or so I get these connection errors in the log, not sure why or how much of a problem this is

[10/03/2023, 08:25:04] [Connexoon] Failed to get the list of events Error: connect ETIMEDOUT 51.79.201.96:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '51.79.201.96',
  port: 443
}
[10/03/2023, 08:25:04] RequestError: Error: connect ETIMEDOUT 51.79.201.96:443
    at new RequestError (/var/lib/homebridge/node_modules/homebridge-connexoon/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/var/lib/homebridge/node_modules/homebridge-connexoon/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/var/lib/homebridge/node_modules/homebridge-connexoon/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/var/lib/homebridge/node_modules/homebridge-connexoon/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.onRequestError (/var/lib/homebridge/node_modules/homebridge-connexoon/node_modules/request/request.js:877:8)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:494:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)

**Comment by yenoiwesa** [comment]
Hello,

These connection timeouts are on the client end. Your local network must be slow or down momentarily. I would check how the homebridge server is connected to the internet in your home. Nothing I can help with on my end unfortunately.

**Comment by Zeses** [comment]
Ok, thank you for the advice ill check and see what's going on here

**Comment by yenoiwesa** [comment]
Have you had any chance investigating your network? I will close the issue for now but don't hesitate to re-open if you found that the problem exists within the plugin.
